export const LOAD_SEARCH_RESULT = 'LOAD_SEARCH_RESULT';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
export const SAVE_SEARCH_TEXT = 'SAVE_SEARCH_TEXT';
export const SAVE_SEARCH_SIZE = 'SAVE_SEARCH_SIZE';